version: '3'
services:
  zn:
    image: siers/zn
    volumes:
      - ~/zn:/work
    links:
      - nsfw
    restart: unless-stopped

  nsfw:
    image: siers/caffe-open-nsfw-server
    volumes:
      - ~/zn/data/down:/data
    restart: unless-stopped

  nginx:
    image: nginx:1-alpine
    volumes:
      - ~/zn/data/down:/usr/share/nginx/html:ro
    ports: ["8080:8080"]
    restart: unless-stopped
