version: '3'
services:
  zn:
    image: siers/zn
    volumes:
      - ~/zn:/work
    links:
      - nsfw
    deploy:
      restart_policy:
        condition: any
        delay: 3s

  nsfw:
    image: siers/caffe-open-nsfw-server
    volumes:
      - ~/zn/data/down:/data

  nginx:
    image: nginx:1-alpine
    volumes:
      - ~/zn/data/down:/usr/share/nginx/html:ro
    ports: ["80:80"]
