name:                zn
version:             0.1.0.0
synopsis:            IRC bot
description:         haskell IRC bot for developers.lv
author:              siers
maintainer:          wimuan@gmail.com
build-type:          Simple
default-extensions:  OverloadedStrings

dependencies:
  - aeson
  - array
  - async
  - base
  - base64-bytestring
  - binary
  - bytestring
  - case-insensitive
  - conduit
  - conduit-combinators
  - conduit-extra
  - connection
  - containers
  - cryptonite
  - data-default
  - either
  - exceptions
  - extra
  - filepath
  - http-client
  - http-client-tls
  - http-types
  - ini
  - irc-client >= 1.0.0.0
  - irc-conduit
  - irc-ctcp
  - lens
  - megaparsec
  - mtl
  - network
  - network-simple
  - process
  - regex-tdfa
  - regex-tdfa-text
  - retry
  - safe
  - split
  - stm
  - stm-chans
  - streaming-commons
  - strict
  - strptime
  - tagged
  - tagsoup
  - telegram-api
  - template-haskell
  - text
  - text-format
  - text-icu
  - text-regex-replace
  - time
  - tls
  - transformers
  - uglymemo
  - unix
  - unix-time
  - unordered-containers
  - x509-system
  - xml-conduit

executables:
  zn:
    ghc-options:    -threaded -rtsopts -with-rtsopts=-N
    source-dirs:    src
    main:           Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - src
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
