resolver: lts-8.17

packages:
- location:
    git: https://github.com/barrucadu/irc-client
    commit: master
  extra-dep: true
- '.'
extra-deps: [
    'encoding-0.8',
    'strptime-1.0.10',
    'http-client-0.5.0',
    'http-client-tls-0.3.3',
    'text-regex-replace-0.1.1.1']

flags: {}
extra-package-dbs: []
system-ghc: false

ghc-build: nopie
ghc-options:
   "$locals": -fwarn-unused-imports
